### ISSUE TITLE
Pygments support?

### ISSUE THREAD

**Issue by captncraig** [ArjenSchwarz/wercker-step-hugo-build#1]
It would be nice if this could install pygments for themes that use it.

Something like 

```
sudo apt-get update -y
sudo apt-get install python-pip build-essential python-dev -y
sudo pip install --upgrade pygments
```

May work. What do you think?

**Comment by ArjenSchwarz** [comment]
Interesting. I wasn't familiar with pygments, but I think it should be possible to do something with this. I'll have a look into it and will let you know what I find. In the meantime, could you point me to a theme that uses it? That way I can have something to test it against.

**Comment by sdebruyn** [comment]
Pygments doesn't depend on the theme :)
When hugo detects pygments and you use the pygments shortcode, hugo generates highlighted code by itself.

E.g.:

```
{{< highlight html >}}
<span>There has been an <strong>awakening</strong>, have you felt it?</span>
{{< /highlight >}}
```

Becomes:

```
<p><div class="highlight" style="background: #272822"><pre style="line-height: 125%"><span style="color: #f92672">&lt;span&gt;</span>There has been an <span style="color: #f92672">&lt;strong&gt;</span>awakening<span style="color: #f92672">&lt;/strong&gt;</span>, have you felt it?<span style="color: #f92672">&lt;/span&gt;</span>
```

</pre></div>
</p>

Details: http://gohugo.io/extras/highlighting/

I'll do a PR with pygments support once [my other PR](https://github.com/ArjenSchwarz/wercker-step-hugo-build/pull/10) is merged to avoid complicating things ;)
