### ISSUE TITLE
Support for Hugo HEAD

### ISSUE THREAD

**Issue by spf13** [ArjenSchwarz/wercker-step-hugo-build#15]
I love this script. It would be amazing if it also supported HEAD (not as default) so I can use this on some of my other sites which often depend on the latest code.

**Comment by ArjenSchwarz** [comment]
I'm glad you like it! And it's certainly something to look into, so I'll probably have a look soon to see how that can be achieved.

**Comment by sdebruyn** [comment]
In this case, the script should install go (`golang-go`) and then run `go get -v github.com/spf13/hugo` and use the generated hugo binary in `$GOPATH/bin/`. Would be quite easy to add, but I don't have the time at the moment. If this issue is still open in a month, I'll submit a PR for it ;)

**Comment by ArjenSchwarz** [comment]
@spf13 this is now possible by setting the version to "HEAD". Please let me know if you run into any issues.
