### ISSUE TITLE
hugo v0.13 support?

### ISSUE THREAD

**Issue by automatonic** [ArjenSchwarz/wercker-step-hugo-build#2]
A [new release](https://github.com/spf13/hugo/releases/tag/v0.13) has dropped. Will this build step automatically support it when i configure the correct version number? Or is a code change needed?

**Comment by ArjenSchwarz** [comment]
@automatonic it is built in such a way that it should automatically support the new version when you set that in the config. I will update the default version soon as well and will let you know once that has happened.

**Comment by ArjenSchwarz** [comment]
Hugo 0.13 is now the default Hugo version. And I've tested this with my own sites as well.

**Comment by automatonic** [comment]
Excellent. Thank you.
