### ISSUE TITLE
Does pygmentize really work on debian boxes? 

### ISSUE THREAD

**Issue by rasteiner** [ArjenSchwarz/wercker-step-hugo-build#22]
https://github.com/ArjenSchwarz/wercker-step-hugo-build/blob/master/run.sh#L102

installs `python3-pygments`, however, it doesn't seem to work (the resulting code block is not highlighted - at least not for me). On localhost, with the same hugo version (0.15), the highlighting works. 

Anyway, on my localhost (ubuntu, so debian based) installing `python3-pygments` in fact **did not** make any `pygmentize` command available. But installing `python-pygments` did. 

In fact: http://pygments.org/download/ refers to a package named `python-pygments` or `pygments`, never `python3-pygments`.

So, I don't know where `python3-pygments` comes from or what it does, but it really doesn't seem to install an executable.

**Comment by ArjenSchwarz** [comment]
Hey @rasteiner, thanks for pointing this out. I've just tried it on a clean Debian container and you're right. While the package description claims that it's pygments written in Python 3, it doesn't actually seem to create any binaries. I'll update the code and roll out a fix for it.
