### ISSUE TITLE
Support Hugo 0.17

### ISSUE THREAD

**Issue by alrayyes** [ArjenSchwarz/wercker-step-hugo-build#26]
Step breaks on 0.17 because Hugo appears to have changed the naming scheme for amd64 version of 0.17:

https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb

Probably an oversight on their part.

**Comment by ArjenSchwarz** [comment]
They changed it again? The naming convention was changed for 15 or 16 as well. I didn't realize 0.17 was released yet, but I'll update the step soon. Thanks.

**Comment by alrayyes** [comment]
That was fast. Looking at their history the naming isn't consequent. Annoying. 0.17 finally has multilingual support. So yay!

**Comment by ArjenSchwarz** [comment]
That is a great reason to quickly support it. But yeah, it was stable for a long time but they've started experimenting with different build systems.

**Comment by ArjenSchwarz** [comment]
This should be fixed with version 1.13.0 which was just released.
