### ISSUE TITLE
Unable to download versions

### ISSUE THREAD

**Issue by jrbasso** [ArjenSchwarz/wercker-step-hugo-build#28]
Seems the filenames changed in Hugo's project, making the default setup (version = 0.17) not to work since the file can't be found.

https://github.com/spf13/hugo/releases/
The new filename: `hugo_0.17_Linux-64bit.tar.gz`
What the script is attempting: `hugo_0.17_linux_amd64.tar.gz`

PS: Other versions have differences too, ie. the `Linux` word in the version 0.16 is lowercase and the extensions is `tgz` instead of `tar.gz`.

**Comment by ArjenSchwarz** [comment]
Thanks @jrbasso, I'll look into this right away.

**Comment by ArjenSchwarz** [comment]
This should be fixed now in version 1.13.1 of the step, which was just released. Hugo 0.17 is included inside the step (but incorrectly until now) so it won't try to download it but use the existing version. I have an open issue (#27) for fixing it in the download for future versions. Thanks again for pointing it out.
