### ISSUE TITLE
box requirements for wercker

### ISSUE THREAD

**Issue by automatonic** [ArjenSchwarz/wercker-step-hugo-build#3]
The example shows `wercker/default` as the box. My project uses node.js to do pre-build steps, and then hugo to do static site generation from there. Does this step depend on anything specific to a box, or is it just downloading the hugo binary release and running it? Ultimately, can i use `wercker/nodejs` as my box basis and still use this step?

(Apologies if there are obvious answers, today is day one of trying to use wercker)

**Comment by ArjenSchwarz** [comment]
Hey @automatonic, yes you should be able to use any box you want with it. I'll update the documentation to reflect this as well. Thanks for your interest and creation of these issues.

**Comment by ArjenSchwarz** [comment]
Hey @automatonic the documentation is now updated to show you can use any box you'd like.

**Comment by automatonic** [comment]
Thanks for clarifying.
