### ISSUE TITLE
Hugo 0.18 build cannot find files

### ISSUE THREAD

**Issue by Jos512** [ArjenSchwarz/wercker-step-hugo-build#30]
I love this Wercker step, so thanks for making it.

When making the step use Hugo 0.18, I get the following persistent error:

~~~
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/pipeline/hugo-build-eb8008c7-d2aa-4fb4-bb1e-140e7834e792/run.sh: line 225: /pipeline/hugo-build-eb8008c7-d2aa-4fb4-bb1e-140e7834e792/hugo_0.18_linux_amd64/hugo_0.18_linux_amd64: No such file or directory
~~~

Based on what I understand from this error message, the step cannot find one of the files. I see that issue #26 (when Hugo 0.17 was released) also had an issue with one of the files not being findable due to changing the names.

-----

I see that the code does this to download Hugo:

~~~
curl -sL https://github.com/spf13/hugo/releases/download/v${WERCKER_HUGO_BUILD_VERSION}/hugo_${WERCKER_HUGO_BUILD_VERSION}_linux_amd64.tar.gz -o ${WERCKER_STEP_ROOT}/hugo_${WERCKER_HUGO_BUILD_VERSION}_linux_amd64.tar.gz
~~~

The [latest release](https://github.com/spf13/hugo/releases/tag/v0.18) doesn't have a **hugo_0.18_linux_amd64.tar.gz** file. It probably (I'm guessing here) has to become https://github.com/spf13/hugo/releases/download/v0.18/hugo_0.18_Linux-64bit.tar.gz .

Hope this additional information makes troubleshooting this issue a bit easier.

Thanks in advance for looking at it.

**Comment by ArjenSchwarz** [comment]
Hi @Jos512, sorry for the late reply but Christmas got in the way.
Thanks for letting me know about this, I completely missed the 0.18 release and as the filenames have been changing I need to do some manual work for it. I should have a version that works with it later today.

**Comment by ArjenSchwarz** [comment]
Hi @Jos512, it was quicker than I thought. Version 1.14 of the build step now supports version 0.18 and uses it by default.
