### ISSUE TITLE
--config not working in flags

### ISSUE THREAD

**Issue by Fale** [ArjenSchwarz/wercker-step-hugo-build#4]
Hi,
adding --config=CONFIG in the flags field (like https://github.com/Fale/fale.github.io/blob/import/wercker.yml) does not work. My guess is that is a problem of paths

**Comment by ArjenSchwarz** [comment]
I'll have a look at this, as it should work. Thanks for letting me know

**Comment by Fale** [comment]
My understanding is that the config file should be passed as:

--config=${WERCKER_SOURCE_DIR}/CONFIG_FILE

Thought, I'm not sure how to test it :(

**Comment by ArjenSchwarz** [comment]
Hi @Fale, you were right about the syntax and I've changed the step so you can now provide a `config` flag in the `wercker.yml` file. This is explained in the README file, and a working example can be found on https://github.com/ArjenSchwarz/hugo-wercker-example.

Thanks for pointing out the problem, and I hope you can now use the step for your site.
