### ISSUE TITLE
Can't make it work with wercker (getting error)

### ISSUE THREAD

**Issue by vapits** [ArjenSchwarz/wercker-step-hugo-build#40]
Hi there,

I have setup my wercker.yml file but when it triesto get the `arjen/hugo-build` it breaks the build.
I'm not sure if it's a bug but I couldn't found anything similar online and therefore I'm posting it here.

Here is my `wercker.yml`:
```yml
box: node
build:
  steps:
    - npm-install
    - arjen/hugo-build:
        version: "1.12.0"
    - script:
        name: Install dependencies
        code: npm install
```
And here's the error:
>export WERCKER_STEP_ROOT="/pipeline/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6"
export WERCKER_STEP_ID="hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6"
export WERCKER_STEP_OWNER="arjen"
export WERCKER_STEP_NAME="hugo-build"
export WERCKER_REPORT_NUMBERS_FILE="/report/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6/artifacts"
export WERCKER_HUGO_BUILD_FORCE_INSTALL="false"
export WERCKER_HUGO_BUILD_BASEDIR=""
export WERCKER_HUGO_BUILD_DEV_FLAGS=""
export WERCKER_HUGO_BUILD_PROD_BRANCHES=""
export WERCKER_HUGO_BUILD_DISABLE_PYGMENTS="false"
export WERCKER_HUGO_BUILD_THEME=""
export WERCKER_HUGO_BUILD_CONFIG=""
export WERCKER_HUGO_BUILD_DEV_BRANCHES=""
export WERCKER_HUGO_BUILD_VERSION="1.12.0"
export WERCKER_HUGO_BUILD_FLAGS=""
export WERCKER_HUGO_BUILD_CLEAN_BEFORE="true"
source "/pipeline/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6/run.sh" < /dev/null
Installing Pyments
Hit http://security.debian.org jessie/updates InRelease
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [509 kB]
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:2 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:3 http://deb.debian.org jessie/main amd64 Packages [9065 kB]
Fetched 9592 kB in 5s (1670 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  python-chardet python-pkg-resources
Suggested packages:
  python-distribute python-distribute-doc ttf-bitstream-vera
The following NEW packages will be installed:
  python-chardet python-pkg-resources python-pygments
0 upgraded, 3 newly installed, 0 to remove and 30 not upgraded.
Need to get 642 kB of archives.
After this operation, 3230 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main python-pkg-resources all 5.5.1-1 [64.4 kB]
Get:2 http://deb.debian.org/debian/ jessie/main python-chardet all 2.3.0-1 [96.2 kB]
Get:3 http://deb.debian.org/debian/ jessie/main python-pygments all 2.0.1+dfsg-1.1+deb8u1 [482 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 642 kB in 1s (610 kB/s)
Selecting previously unselected package python-pkg-resources.
(Reading database ... 21217 files and directories currently installed.)
Preparing to unpack .../python-pkg-resources_5.5.1-1_all.deb ...
Unpacking python-pkg-resources (5.5.1-1) ...
Selecting previously unselected package python-chardet.
Preparing to unpack .../python-chardet_2.3.0-1_all.deb ...
Unpacking python-chardet (2.3.0-1) ...
Selecting previously unselected package python-pygments.
Preparing to unpack .../python-pygments_2.0.1+dfsg-1.1+deb8u1_all.deb ...
Unpacking python-pygments (2.0.1+dfsg-1.1+deb8u1) ...
Setting up python-pkg-resources (5.5.1-1) ...
Setting up python-chardet (2.3.0-1) ...
Setting up python-pygments (2.0.1+dfsg-1.1+deb8u1) ...

>gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Cleaning the public directory
Running the Hugo command
/pipeline/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6/run.sh: line 257: /pipeline/hugo-build-7f409aef-740f-4807-b60e-374d1ca6c6e6/hugo_1.12.0_linux_amd64/hugo_1.12.0_linux_amd64: No such file or directory

**Comment by lluvio** [comment]
@vapits 
hi, I have the same problem, how did you fixed it?
