### ISSUE TITLE
Build failed with getAllStepVars: command not found

### ISSUE THREAD

**Issue by Skarlso** [ArjenSchwarz/wercker-step-hugo-build#47]
Hey man.

The latest run failed with this weird error:

```
run.sh: line 5: getAllStepVars: command not found
```

Any ideas? Cheers.

**Comment by Skarlso** [comment]
@ArjenSchwarz ping?

**Comment by Skarlso** [comment]
So, I found out what's wrong. This is a very bad case of terrible error message. The GIT_TOKEN environment property was missing. That's what went wrong.

**Comment by ArjenSchwarz** [comment]
HI @Skarlso, apologies for not coming back earlier. When you filed the issue I was at re:Invent and missed the notifications about this.

It's been fixed now apparently, but based on the information you've provided I also feel like the error might not have been in this step as it doesn't use a GIT_TOKEN. Was this indeed the case, or is there something that needs to be fixed?

**Comment by Skarlso** [comment]
@ArjenSchwarz no worries man. Yeah, sorry, I think what actually happened it that I accidentally revoked access for the token I specified. So it was there, it just wasn't valid. Thus the error is totally confusing because it didn't tell me that I didn't have the rights to deploy but instead threw that at me. :)
