### ISSUE TITLE
hugo extended version not being installed

### ISSUE THREAD

**Issue by vvasuki** [ArjenSchwarz/wercker-step-hugo-build#48]
Hi!

After [this build](https://app.wercker.com/vvasuki/saMskAra/runs/build/5c299ba5c0c3d7001195df80?step=5c299bbecfa0fc00073eaa1a) made me realize that I need the [hugo extended binary](https://discourse.gohugo.io/t/this-feature-is-not-available-in-your-current-hugo-version/12831/12); I tried passing version number extended_0.53, which [also fails](https://app.wercker.com/vvasuki/saMskAra/runs/build/5c2a4b251eea2b000779d136?step=5c2a4b3fcfa0fc0007400da7). Could you fix/ help?

**Comment by ArjenSchwarz** [comment]
Hi @vvasuki,

Thanks for pointing this out. As I don't use the functionalities of the extended version, I didn't even realise those are not included in the default binary. I'm planning to release an updated version that uses the extended binary very soon (likely today).

**Comment by ArjenSchwarz** [comment]
Hi @vvasuki,

Version 2.8 of the step will now by default use the extended version of Hugo where this is available (every version from 0.43 upwards). I hope this helps you.

Cheers,

Arjen

**Comment by vvasuki** [comment]
I am so happy to see [my build](https://app.wercker.com/vvasuki/saMskAra/runs/build/5c2ae28bc0c3d7001196065e?step=5c2ae2a5cfa0fc0007409a4f) succeed again. Thanks very much!
