### ISSUE TITLE
Not working if there is no theme

### ISSUE THREAD

**Issue by Fale** [ArjenSchwarz/wercker-step-hugo-build#6]
I guess that this is also caused by some path problems, not giving the theme (since I have all in /layouts  and /statis) I receive the following errors:

```
ERROR: 2015/04/25 Unable to render [page/list.html _default/list.html theme/page/list.html theme/_default/list.html]
ERROR: 2015/04/25 Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [page/list.html _default/list.html theme/page/list.html theme/_default/list.html]
```

Thanks a lot :)

**Comment by ArjenSchwarz** [comment]
OK, looks like some more work needs to be done then. It's late here, so I'll have a look in the morning.

**Comment by Fale** [comment]
Thanks :)

**Comment by ArjenSchwarz** [comment]
Actually, I just had a few minutes to take a look. As my main blogs also don't use a theme, I wanted to see why it wouldn't work for you here. I took the liberty of cloning your repository and trying the build command locally and it gave the same error. You seem to be missing a default `list.html`, which it needs for your pages. 
I assume you might not actually link to this list anywhere on your site, but Hugo requires it anyway. The easiest way to deal with this is to add a basic `list.html` template in your `_default` directory (possibly copy the one you have for posts).

Let me know if this helps.

**Comment by Fale** [comment]
Thanks a lot, it solved :)

Probably I have a hugo version that is slightly different because mine does not complain.
