### ISSUE TITLE
Issue with version in wercker build

### ISSUE THREAD

**Issue by herveDarritchon** [ArjenSchwarz/wercker-step-hugo-build#9]
Hi,

I have an issue when running wercker build with this wercker.yml
I had to change the container because of the issue #8

```
box: python:wheezy
build:
  steps:
    - arjen/hugo-build:
        version: 0.14
        theme: hd-theme
        flags: --disableSitemap=true
```

the version is not assign to the run.sh variable ${WERCKER_HUGO_BUILD_VERSION} so it is replaced by a false

--> Running step: wercker-init
--> Running step: hugo-build
--2015-06-02 15:41:23--  https://github.com/spf13/hugo/releases/download/vfalse/hugo_false_linux_amd64.tar.gz
Resolving github.com (github.com)... 192.30.252.128, 192.30.252.128
Connecting to github.com (github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-06-02 15:41:24 ERROR 404: Not Found.

tar (child): hugo_false_linux_amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/pipeline/hugo-build-fd42a7dd-678b-4ea4-b6f2-e8f6539facfe/run.sh: line 21: /pipeline/hugo-build-fd42a7dd-678b-4ea4-b6f2-e8f6539facfe/hugo_false_linux_amd64/hugo_false_linux_amd64: No such file or directory
--> Step failed: hugo-build
--> Pipeline failed

If I change the wercker.yml and suppress the version to get the default value (which is 0.14), then it runs smoothly.

**Comment by ArjenSchwarz** [comment]
Thanks for pointing this out. I suspect it is probably related to the same thing as I mentioned in your bug report #8, and I'll take this into account while I look at that one.

**Comment by ArjenSchwarz** [comment]
I have been able to replicate this in a Docker build myself, and will fix it. There are some other changes I will need to make for complete compatibility as well, such as wget not being available on the default debian box.

**Comment by ArjenSchwarz** [comment]
Hey @herveDarritchon, it looks like this is actually an issue with Wercker's yaml parser which for some reason turns any 0.x based string into false. The easiest way to solve this is to put quotes around the version number e.g. `version: "0.14"` in your wercker.yml file.
I have updated the step to no longer fail on this though, and now it will use the latest version of Hugo if it receives false as the version number.
